# These are supported funding model platforms

github: balaga-yavanika
BMC: buymeacoffee.com/whyaweeye25
custom: ["https://www.buymeacoffee.com/whyaweeye25", "https://www.buymeacoffee.com/whyaweeye25"]
