# # These are supported funding model platforms

# github: sethcottle
# patreon: sethcottle
# ko_fi: sethcottle
custom: ["https://www.buymeacoffee.com/whyaweeye25", "https://www.buymeacoffee.com/whyaweeye25"]
